### ISSUE TITLE
Unable to access DOM from loaded page

### ISSUE THREAD

**Issue by nadir1122** [MicrosoftEdge/WebView2Samples#11]
DOM elements and their properties cannot be accessed like they were in Internet Explorer

**Comment by pagoe-msft** [comment]
Hi nadir1122,

That's correct, unlike with MSHTML Browser Control, in WebView2 DOM elements and their properties cannot be accessed. Could you please explain your scenario (what you're trying to accomplish) that requires accessing DOM elements?

**Comment by nadir1122** [comment]
I want to Access properties of loaded document. Like Document HTML, its meta tags, HTML DOM element properties etc. 
as you know that programmers use webView not just to display html, we intend to do much more than this. If we just want to display HTML, then external browsers are fine. but we need to handle web browser properties and document properties which we embed in our Application.

**Comment by pagoe-msft** [comment]
Hi nadir1122,

You can access the HTML DOM and element properties via JavaScript. For example, "document.getElementById()" returns a list of elements with the specified ID. These DOM functions exist in JavaScript for classes, tags, etc. You can then use the ExecuteScript() function to run JavaScript code.

**Comment by nadir1122** [comment]
How can i inject javascript code into document? a page which is loaded by a URL given by application user.

**Comment by pagoe-msft** [comment]
You can refer to some of our docs:

Step 6 of our getting started guide details 'communication between the host and web content'.
https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/gettingstarted

You can learn more about the ExecuteScript() function here:
https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#executescript
