### ISSUE TITLE
Is there a way to use default browser cookies inside WebView2 control?

### ISSUE THREAD

**Issue by gileli121** [MicrosoftEdge/WebView2Samples#112]
Hello, I want that the WebView2 control will able to support any cookies from chromium-based browsers.
So if the default user browser is Google Chrome, the WebView2 control will use the current user cookies from Google Chrome.
And if the default user browser is Edge, the WebView2 control will use the current user cookies from Edge.

Is it possible somehow?
Thanks.

**Comment by champnic** [comment]
Hey @gileli121 - No, this is not currently possible and is By Design for security reasons. Thanks!
