### ISSUE TITLE
`SampleApps\webview2_sample_uwp` references a missing file

### ISSUE THREAD

**Issue by ppena-LiveData** [MicrosoftEdge/WebView2Samples#114]
`Properties\Default.rd.xml` is referenced by [the VS project](https://github.com/MicrosoftEdge/WebView2Samples/blob/5b3625aa547d59647a7363799d1c1b413bce078c/SampleApps/webview2_sample_uwp/WebView2_UWP.csproj#L135), but that file does not exist, so that causes an error when trying to build.

**Comment by oggy22** [comment]
Thank you for the feedback! We should fix this soon.

**Comment by oggy22** [comment]
@ppena-LiveData I added the file and made sure the app builds and runs correctly. Please let me know if doesn't for you.
