### ISSUE TITLE
WebView2- 'Page is Having a Problem’ Error on Microsoft Edge Project

### ISSUE THREAD

**Issue by ncidiri** [MicrosoftEdge/WebView2Samples#115]
Hi All

i have installed Microsoft.Web.WebView2(1.0.1054.31) in my project, written code to open the website, some days back functionality was worked fine

now the same code is not working in the debug mode and same code is working for others machines after adding below registry values (RendererCodeIntegrityEnabled=0 ,DisabledComponents=0 )

My machine configuration:
Edge version is 96.0.1054.62
Windows 10 OS

Visual studio 2019 with C# code, 4.8 dot net framework version

Edge is working fine for normal browsing

i have added below in the registry settings
RendererCodeIntegrityEnabled=0
DisabledComponents=0

while excution of code getting error like ‘Page is Having a Problem’ window while loading the website .
any thoughts/solution

Thanks
Nag

**Comment by champnic** [comment]
This is an error with WebView2, not the samples specifically. Please open an issue in our feedback repo if you'd like us to look into this:
https://github.com/MicrosoftEdge/WebView2Feedback/issues

Thanks!
