### ISSUE TITLE
System.Windows.Forms.WebBrowser.Document WebView2 equivalent

### ISSUE THREAD

**Issue by jwilburn** [MicrosoftEdge/WebView2Samples#121]
trying to update some legacy code with `WebView2` and can't find an equivalent property for `System.Windows.Forms.WebBrowser.Document`, https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.webbrowser.document?view=windowsdesktop-6.0

is there a property that supports this functionality off the base object and or CoreWebView2?

**Comment by champnic** [comment]
Hey @jwilburn - WebView2 doesn't give direct access to DOM elements. Instead you should use `ExecuteScriptAsync` to run script that manipulates the DOM as you need it. More info on native <-> web interop is here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/communicate-btwn-web-native

We are tracking adding support for HTML/DOM access here:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/77

**Comment by jwilburn** [comment]
Hey @champnic, I don't need to manipulate the DOM, I just access to a property that would return the entire HTML document. Is that available?

**Comment by champnic** [comment]
You should be able to do something like `var html = ExecuteScriptAsync("document.body.innerHTML;");`.
