### ISSUE TITLE
When calling 'CreateCoreWebView2Controller' in Webview2, it takes about 3 seconds, but I want to reduce it to 1 second. I wonder if there is a better way.

### ISSUE THREAD

**Issue by jaehojung** [MicrosoftEdge/WebView2Samples#138]
Hello, my name is Jaeho.
I wonder how is solves that calling 'CreateCoreWebView2Controller' in Webview2(win32, version 1.0.1072.54), it takes about 3 seconds, but I want to reduce it to 1 second. I wonder if there is a better way.

**Comment by xiaoyaocode163** [comment]
YOU CAN CreateCoreWebView2Controller IN BACKGROUND,by thread.
you make 10 webview control
if you want to use ,only do "showweb(1)
showweb(2)
showweb(3)

**Comment by xiaoyaocode163** [comment]
so it's only used 1 ms
