### ISSUE TITLE
Getting Started Code

### ISSUE THREAD

**Issue by aarupaliya** [MicrosoftEdge/WebView2Samples#143]
It looks like this is your first time opening an issue in this project! @yildirimcagri @fabiorocha @travisleithead 
ithin the <PackageFiles CopyAllPackageFiles="false"> and </PackageFiles> section, un-comment the line <PackageFile Name="MicrosoftEdgeWebview2Setup.exe" />, and comment out other lines.
Within the <Commands Reboot="Defer"> and </Commands> section, make sure PackageFile points to "MicrosoftEdgeWebview2Setup.exe" so that the VS installer would be using the Bootstrapper.
For "Download the Evergreen WebView2 Runtime Bootstrapper through link",
Within the <PackageFiles CopyAllPackageFiles="false"> and </PackageFiles> section, un-comment the line <PackageFile Name="MicrosoftEdgeWebview2Setup.exe" HomeSite="WebViewRuntime" PublicKey="..."/>, and **bug**comment out other lines. Note that the PublicKey for the WebView2 Runtime Bootstrapper may change without notice and we are working on addressing this issue. For now, you may need to replace it with an updated PublicKey.
Within the <Commands Reboot="Defer"> and </Commands> section, make sure PackageFile points to **"MicrosoftEdgeWebview2Setup.exe" so that the VS installer would be using the Bootstrapper.**
For "Package the Evergreen WebView2 Runtime Stand

**Comment by champnic** [comment]
This doesn't look like a bug. Let me know if you have a specific issue and we can revisit. Thanks!
