### ISSUE TITLE
UWP application doesn't run on vanilla Windows 10 installation

### ISSUE THREAD

**Issue by ramondeklein** [MicrosoftEdge/WebView2Samples#145]
I have issues (see https://github.com/MicrosoftEdge/WebView2Feedback/issues/2640) running WebView2 in my UWP application, so I tried to run the UWP sample in this repo. I performed the following steps:

1. Build the [UWP sample](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/webview2_sample_uwp) in Visual Studio 2022 and package it.
2. Install the digital signature to the local machine's root CA to be able to install the package.
3. Install the package on my development machine and it runs without any issues.

Now I try the same on my Windows 10 machine:
1. Install the WebView2 runtime using the [Evergreen bootstrapper](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section).
2. Reboot the machine.
3. Install the digital signature to the local machine's root CA to be able to install the package.
4. Install the package on my development machine and the apps runs, but only shows a blank page where it showed the web-view on my development box.

**Comment by ramondeklein** [comment]
When I uninstall the WebView2 runtime and install it using admin-privileges, then it does seem to start.

**Comment by champnic** [comment]
@ramondeklein Sounds like the admin-level runtime resolved this issue. If there was something else we should be fixing please let me know and I can reactivate. Thanks!

**Comment by ramondeklein** [comment]
I have filed a PR to also mention this in the README, so other users may be better informed about this.
