### ISSUE TITLE
.Net Framework 4.6 in the samples?

### ISSUE THREAD

**Issue by Terrence77** [MicrosoftEdge/WebView2Samples#187]
I downloaded the samples and attempted to run the WindowsFormsBrowser and could not because the project was targeting

`<TargetFrameworks>net462</TargetFrameworks>`

Why would MS be posting samples of a brand new WebView2 in a project that is targeting code from a distant past.

Where are the samples using .NetCore?

Thank you.

**Comment by Terrence77** [comment]
Is this repository being monitored by MS?

**Comment by champnic** [comment]
Hey @Terrence77 - Yes, though not as closely as the WebView2Feedback repo.

To answer your question above - our default is to support as far back as we can, as we have lots of different customers using different frameworks, many of who are migrating old apps. You should be able to retarget the project, or if you want to create a new one targeting .NET Core or 5/6/7, the WebView2 code should be the same.

**Comment by Terrence77** [comment]
@champnic  Thank you for that explanation.
