### ISSUE TITLE
Problem in README.md (links and images)

### ISSUE THREAD

**Issue by rflsouza** [MicrosoftEdge/WebView2Samples#19]
First, congratulations on the documentation and examples!

I maintain some C ++ code for Microsoft (MFC and Win32) and it is increasingly difficult to find good documentation for this.

I'm thinking of using WebView2, I used CEF a while ago, but I didn't like how it worked, with this API everything is easier to maintain! 

Can you tell me when Edge with chromium becomes official and will be updated directly on windows?

**about the problems are two:**
**1)** [Images ](https://github.com/MicrosoftEdge/WebView2Samples/tree/master/WebView2APISample)are not showing in the browser, it appears broken.
**2)** In (RegisterEventHandlers) the documentation link is wrong. In the part (To read more about event handlers in WebView2, you can refer to this **documentation**.)

**Comment by pagoe-msft** [comment]
Hey @rflsouza,

Thanks so much for bringing this to our attention! I've updated the images and links - they should all work now. I'd really appreciate if you could let us know some of the pain points you've had with CEF - this can help us improve the developer experience in WebVIew2.

We don't have an official date yet for when the new Edge Browser will be directly updated on Windows, but once that date is made official I'll return here.

Thanks!

**Comment by rflsouza** [comment]
I use an application made in MFC, at the time I used CEF there was a wrapper and also a class for the API implementation, whenever there was an update it was very complicated to update, not counting the work when changing the APIS, it had to stay redoing everything. This got complicated and I even stopped using it, now I'm testing webview2 and I'm really enjoying the simplicity. Besides said it was a huge consumption of memory, I believe it has improved.

An advantage of CEF is that you do not need to have the browser installed on the operating system, you can send the DLLs to work with your application. It would be interesting to be able to do this with webview2.

Some things I'm still testing and it's still complicated for me to use is that webview2 is asynchronous. I did a project to test with [MFC ](https://github.com/rflsouza/WebView2BrowserMFC_MDI)and tried to synchronize when the events are ready, but I still haven't found a way! If I can't find anything, I'll ask for your help! :)

Thanks for the project! I am really learning a lot and things using new libs, it is difficult nowadays to find C ++ projects for windows (win32).
