### ISSUE TITLE
Unity Hololens 2 sample crashes at startup

### ISSUE THREAD

**Issue by ptc-ccrabb** [MicrosoftEdge/WebView2Samples#193]
I have enrolled my HoloLens in Windows Insider program, using the "Dev" channel. It is running version `22621.1083.arm64fre.ni_release_svc_sydney.230514-1300` and I have reproduced the crash on a fresh reboot.

The debug output in Visual Studio contains this big hint:

> WebView2: Failed to find an installed WebView2 runtime or non-stable Microsoft Edge installation.

According to https://learn.microsoft.com/en-us/hololens/hololens-insider#windows-insider-release-notes the WebView2 component should be available in build `10.0.22621.1061` -- I think my installed version ( `22621.1083` ) is newer.

I have made the changes in my Package.appxmanifest as described at https://learn.microsoft.com/en-us/hololens/hololens-insider#webview2-now-available

I have tried to manually install the Dev channel of Microsoft Edge following the instructions at https://www.microsoftedgeinsider.com/en-us/download?platform=hololens2. The installers fail to launch on my HoloLens.

The Mixed Reality Feature Tool is bringing in version 0.17.1-pre.3 of com.microsoft.mixedreality.webview.unity.

Running the sample app through Unity's play mode works just fine.

Is there some change I can make to enable development/exploration of the WebView2 component in a Unity app on a HoloLens 2?

**Comment by SamiraAtMicrosoft** [comment]
Hi @ptc-ccrabb,

Out of curiosity, have you tried any of the other WebView2 samples on your HoloLens 2 and do you encounter the same error? For instance, there is also a WinUI2 UWP sample (that would also need the package.appxmanifest update).

Also, are you running Debug or Release on your device?

**Comment by SamiraAtMicrosoft** [comment]
Thank you for the details. Very strange! 
On your Device Portal can you navigate to `Views` -> `Apps`. Under `Installed apps`, can you select `Show framework packages` and look for `Microsoft WebView2 Runtime`.  (It normally appears just before the "Microsoft.UI.Xaml.*" items.) 
Does it appear at all in this list? If it does, can you select it and copy and paste the details that are output once you select it?

Also, do you recall the build you were on prior to updating to `22621.1083.arm64fre.ni_release_svc_sydney.230514-1300`?

**Comment by ptc-ccrabb** [comment]
I don't see a `Microsoft WebView2 Runtime`, but I do see `Microsoft.WebView2Runtime.Stable` with the following details:

> Version: 112.0.1722.58
> Publisher: CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
> PackageFullName: Microsoft.WebView2Runtime.Stable_112.0.1722.58_arm64__8wekyb3d8bbwe


I don't recall what version I had prior to enrolling in Windows Insider, but I do know that I had gone to Windows Update in Settings and manually checked for and installed all updates then rebooted and checked for updates again prior to enrolling in Windows Insider.

When I enrolled in Windows Insider I first selected the `Release Preview` channel and let it install. I later found the documentation that stated that the `Dev` channel was required and then moved to that channel.

**Comment by JordanMandel** [comment]
If you still have your device in the same state, could you please log a feedback bug using the Feedback Hub and select the category of Updates please? Thanks!

**Comment by ptc-ccrabb** [comment]
Feedback captured as `ccrabbptc@gmail.com` with title `Failed to initialize WebView2 on HoloLens2 at version 22621.1083.arm64fre.ni_release_svc_sydney.230514-1300`.

There wasn't a category of `Updates` but there was both `Install and Update` and `Windows Setup and Update` -- I've filed under `Install and Update` => `Post-update app experience`.

I don't see any unique identifier when viewing the feedback in Feedback hub, so don't know how to directly link you to it.

Next week I'll try flashing the device directly to the dev stream to see if that fixes the problem.

**Comment by SamiraAtMicrosoft** [comment]
Thank-you @ptc-ccrabb - we received your Feedback Hub bug report and are investigating the issue.

**Comment by ptc-ccrabb** [comment]
I was able to flash my device back to FE_RELEASE_SVC_SYDNEY_REL_PROD.retail.multi.10.0.20348.1543.ffu then enroll in the Dev channel of Windows Insider and the got the WinUI2 sample working on my HoloLens.

In my own project I've gotten the Unity WebView2 component working with basic click input.

I was unable to get the Microsoft-authored sample Unity WebView2 project working, I may take another pass at if after I get full input working in my project.

**Comment by michaelfarnsworth** [comment]
Glad to hear you were able to get the WinUI2 sample working.

I would be interested to learn some more details on the issues you had with the Unity-based sample.

**Comment by michaelfarnsworth** [comment]
Currently, this Github repo is the best place. Please, feel free to open an issue. Input is an area we're looking to improve.

**Comment by Bobypaliya1** [comment]
Issue by #193
