### ISSUE TITLE
Null Reference Exception when trying to run the WinForms sample project

### ISSUE THREAD

**Issue by Astral100** [MicrosoftEdge/WebView2Samples#215]
As the title says, I can't even run the `WinForms_GettingStarted` sample:

![image](https://github.com/MicrosoftEdge/WebView2Samples/assets/26874956/da3f215e-ba7f-4551-b78a-235366caf17c)

Tried on both Visual Studio 2019 and 2022. Both are run as administrator.

My OS is Windows 10.

I also tried installing latest WebView2 runtime, and it didn't help. 

What is going on?

P.S. When I tried following tutorial to create project from scratch, I was able to follow this tutorial until step 5 (inclusive):
https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms
and it was working as expected (I was able to see microsoft website appearing as expected)

**Comment by champnic** [comment]
Hey @Astral100 - Which object is null in the failure? And when you follow the steps, it sounds like the WebView2 was running fine, but that something about adding the other controls in step 6 resulted in a crash?

**Comment by Astral100** [comment]
Hello, after playing around with WebView2 for a few days I can't reproduce it anymore. The sample project runs fine now.
I imagine it might have something to do with me installing and uninstalling webview2 runtime several times from my system after reporting the bug.
It could be caused by old version of Edge runtime originally installed on my system.
I am closing it down for now.

**Comment by champnic** [comment]
Thanks for confirming @Astral100, and glad you are no longer hitting this issue.

**Comment by ajstadlin** [comment]
I get this same exception.  Visual Studio 2022 Pro, Version 17.11.5, Microsoft.Web.WebView2 Runtime version: v4.0.30319. Steps to repeat = Clone the WebView2Samples project, open the WinForms_GettingStarted.sln, Run in Debug mode, AnyCPU

**Comment by ajstadlin** [comment]
This problem went away for me after installing the latest nuget update for Microsoft.Web.WebView2
