### ISSUE TITLE
UWP Sample

### ISSUE THREAD

**Issue by anovik** [MicrosoftEdge/WebView2Samples#28]
Is it possible to add sample how to use WebView2 in UWP application?

**Comment by adambarlow** [comment]
Hi, yes, we do! We have a sample gallery app that has a WebView2 in it. You can find the source code here:
https://github.com/microsoft/Xaml-Controls-Gallery/tree/winui3preview

**Comment by anovik** [comment]
Could you please tell me whether I need to include both Microsoft.Ui.Xaml and Microsoft.Web.WebView2 nuget packages to start using WebView2 in my UWP project?

**Comment by adambarlow** [comment]
As of the new Preview 1 we pushed this Tuesday at //BUILD you only need to have the WinUI nuget.

**Comment by anovik** [comment]
Thanks, this is clear now! 

But in the sample you've pointed out WebView from Windows.Ui.Xaml.Controls namespace is used, it seems it is old namespace, not Microsoft.UI.Xaml.Controls? How should we switch from webview to webview2 in uwp apps?

**Comment by ramondeklein** [comment]
@adambarlow I think this issue is resolved a while back.

**Comment by champnic** [comment]
Good callout @ramondeklein - We indeed have a UWP sample app, based on WinUI 2.
https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/webview2_sample_uwp
