### ISSUE TITLE
Possible to view-source:url in code?

### ISSUE THREAD

**Issue by daniel-rck** [MicrosoftEdge/WebView2Samples#38]
Hello,
I'm doing a little sample application with WebView2. I try to get the source-code of the current page,
the same as you can see in e.g. `view-source:https://www.bing.com/`
Is this possible from within C#?

Already did this with javascript, but there is missing data in comparison to the browser variant.

            try
            {
                string html = await webView.CoreWebView2.ExecuteScriptAsync("document.documentElement.outerHTML");
                string unescaped = Regex.Unescape(html);
                html = unescaped.Substring(1, unescaped.Length - 2).Replace("&amp;", "&");

                if (!html.StartsWith("<html"))
                {
                    Debug.WriteLine("Invalid source");
                    return null;
                }
                var doc = new HtmlDocument();
                doc.LoadHtml(html);
                return doc;
            }
            catch (Exception exc)
            {
                Debug.WriteLine(exc.Message);
                return null;
            }
`

**Comment by pagoe-msft** [comment]
Currently, there isn't a way via C#. If you don't mind can you resubmit this as a feature request here: 

https://github.com/MicrosoftEdge/WebViewFeedback/issues

**Comment by daniel-rck** [comment]
Thanks for your answer, @pagoe-msft I will submit an new request there (https://github.com/MicrosoftEdge/WebViewFeedback/issues/296) and close this one.
