### ISSUE TITLE
How to load flash plugin in winfrom?

### ISSUE THREAD

**Issue by westinyang** [MicrosoftEdge/WebView2Samples#40]
I use VS2019 + Windows Form + WebView2 (0.9.538-prerelease)，There are no problems with the development environment or project operation，But the web doesn't seem to be able to load the Flash plug-in。

**Comment by champnic** [comment]
Hey @westinyang - The WebView2 control doesn't support Flash and we don't have plans to support it in the future. The browser in general is moving towards removing Flash support. Thanks for the question and trying out WebView2!

**Comment by JoshuaWeber** [comment]
For more context see: https://docs.microsoft.com/en-us/lifecycle/announcements/adobe-flash-end-of-support Flash is reaching end of life across all products this year. Given the short time window before end of life we will not support it for WebView2.

**Comment by westinyang** [comment]
> Hey @westinyang - The WebView2 control doesn't support Flash and we don't have plans to support it in the future. The browser in general is moving towards removing Flash support. Thanks for the question and trying out WebView2!

The Edge browser alone supports Flash, but asks the user if he or she is allowed to play flash.Although the browser is the development trend of phased out falsh, but for now, the mainstream browsers will support flash, because the application is very extensive, such as video on demand business of education industry, many still stays in the flash player, there are many web games also in the use of flash, of course there are other niche usage scenarios.I don't think flash should be thrown away entirely. At least for developers, it should be possible to configure the embedded browser component to support Flash.I also need this feature in my current business, so I suggest that the embedded browser plug-in should retain Flash support for developers.
