### ISSUE TITLE
Linux and macOS support?

### ISSUE THREAD

**Issue by trusktr** [MicrosoftEdge/WebView2Samples#41]
Is this planned for the future of WebView2?

**Comment by pagoe-msft** [comment]
@trusktr,

This is the direction we would like to go, but don't expect to support Linux and macOS in the near future.

**Comment by kitingChris** [comment]
You should really reconsider this... WebView2 with Linux and macOS would have the potential to be a successor of electron.

**Comment by champnic** [comment]
MacOS support has begun and is tracked here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1314
Linux support will come later and is tracked here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/645

Thanks!
