### ISSUE TITLE
Address bar URL throws an error if URL does not start with http or https

### ISSUE THREAD

**Issue by srazasyed** [MicrosoftEdge/WebView2Samples#44]
When working on `WebView2WpfBrowser` sample, I get the following error at the following code in `MainWindow.xaml.cs` file. The sample runs fine except when in the `address bar` I type a URL without using `http://` or `https://` and click on `Go` button next to the address bar. It throws the following error if you, for example, just type `microsoft.com` or even `www.microsoft.com`.

**Error**:
>>System.UriFormatException
  HResult=0x80131537
  Message=Invalid URI: The format of the URI could not be determined.
  Source=System.Private.Uri

**Code**:

    void GoToPageCmdExecuted(object target, ExecutedRoutedEventArgs e)
    {
        webView.Source = new Uri((string)e.Parameter);
    }

  [1]: https://docs.microsoft.com/en-us/microsoft-edge/webview2/
  [2]: https://github.com/MicrosoftEdge/WebView2Samples

**Comment by jarno9981** [comment]
Yeah me tp in winforms no http or https throws error

**Comment by jarno9981** [comment]
@champnic  , do you now how to fix if no http or https is used in url  is it possible without

**Comment by champnic** [comment]
This is just the way the sample app is currently coded. In your own code you can take a user's input and just prepend "https://" or other protocol scheme if it's missing. I'll open a bug on our backlog for this.

**Comment by peiche-jessica** [comment]
We've updated WebView2WpfBrowser and WebView2WindowsFormsBrowser to address this!
