### ISSUE TITLE
WebView2 using canary - why not release edge browser

### ISSUE THREAD

**Issue by praburamb** [MicrosoftEdge/WebView2Samples#50]
All,
I have created com interop control to use in VB6, it is working fine with minor issues.
But edge canary should be installed in that machine. Since edge canary is not released on how can we use that control in production. Please help me.

Is it works in regular edge chromium?

Thanks
Prabu

**Comment by champnic** [comment]
In future please use the Feedback repo for issues and questions :) https://github.com/MicrosoftEdge/WebViewFeedback

For release/production you should use the WebView Runtime Installer, please see this documentation:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

If you have specific questions after looking there please let me know and I can answer it.

**Comment by praburamb** [comment]
Thanks for your immediate response. I tried with  WebView Runtime Installer (Preview) and uninstalled canary. Good news is  still it is working fine in VB6. But my question is  since it is Preview version, can't release with this in my product. is there any work around to run my product in all the machines.

**Comment by champnic** [comment]
The WebView2 control itself is still in prerelease/preview, so I wouldn't recommend releasing to production now anyways. The Runtime Installer will be released later this year at the same time as the Win32 control (Oct/Nov), and then the .NET controls will be after that (probably Nov/Dec).

**Comment by champnic** [comment]
Thanks for moving the discussion over to the feedback repo :)
https://github.com/MicrosoftEdge/WebViewFeedback/issues/385
