### ISSUE TITLE
WebView2APISample fails to start, "abort() has been called"

### ISSUE THREAD

**Issue by rotoglup** [MicrosoftEdge/WebView2Samples#64]
Went starting the WebView2APISample in *Debug* configuration, it stops just after showing the window, with a modal dialog.

![image](https://user-images.githubusercontent.com/926098/100152221-a43d6a00-2ea2-11eb-8625-c83278977fde.png)

When starting in Release, it exits without message just after showing briefly the window.

I did the following steps to test the sample :

* cloned the master branch (commit eecf3846b7f2b2)
* upgraded my Edge to Version 87.0.664.47 (64 bits)
* installed WebView2 Runtime (evergreen @ 87.0.664.47)
* built with Microsoft Visual Studio Community 2019, Version 16.8.2
* on Windows 10 Pro, Version	10.0.19041 Numéro 19041

I was unable to get a proper call stack, the error happens in the message pump's "external code".

Please find the [console-output](https://github.com/MicrosoftEdge/WebView2Samples/files/5592814/console-output.txt) attached.

**Comment by kernel1983** [comment]
I have the same issue, the release version crash as well.

**Comment by champnic** [comment]
Thanks for the report! The Sample app currently uses a lot of the experimental APIs that are only supported in the latest Edge Dev or Canary build. For example, currently the sample app uses 1.0.707-prerelease SDK, so needs to use a runtime 89.0.707+.

We realize this is a pain point, and we do want our Sample app to be able to work with the latest runtime, so we are planning work to make this better.

**Comment by rotoglup** [comment]
@champnic Thanks for your feedback.

if I may  : I think a clear mention of what you indicated in the README would be a nice addition, it would save much time and trouble to potential testers around.
