### ISSUE TITLE
Where can I get up to date public key for bootstrapper?

### ISSUE THREAD

**Issue by Kyeongdon-Lim** [MicrosoftEdge/WebView2Samples#65]
Hello, 

I'm trying to make bootstrapper package for deploy WebView2 via clickonce.

I followed bootstrapper example in  'WV2DeploymentVSInstallerSample'.

But, I have problem with WebView2 download link.
I guess the key has changed.

 Error message is popuped when try install like below.
'Setup has detected that the file ***\MicrosoftEdgeWebview2Setup.exe' has changed since it waw initially published. Click OK to retry the download, or Cancle to exit setup.'

So maybe I need new public key for fix this problem.

Where can I get the key?

**Comment by champnic** [comment]
Thanks for using WebView2! We actually don't recommend using the VS Installer to do the download at the moment. The download link payload will change pretty often, and when it does will require a new key. If you deploy your app and the public key changes then the download will fail with the error message you received. 

You can get a new key by downloading the MicrosoftEdgeWebview2Setup.exe manually, right-click > Properties > Digital Signatures tab > Microsoft Corporation cert > Details > View Certificate > Details tab > Public Key field. Phew! Writing that out made me realize how many steps it is...
![image](https://user-images.githubusercontent.com/45700886/101123137-f9673300-35a8-11eb-9b2f-cba7e622a4c7.png)

**Comment by Kyeongdon-Lim** [comment]
@champnic  Thank your for your answer! 
As your recommendation, I will find other way for deploying app.
