### ISSUE TITLE
The sample WebView2APISample app Aborts

### ISSUE THREAD

**Issue by HoldenPCaulfield** [MicrosoftEdge/WebView2Samples#73]
Cloned the sample code and i get the following after building and starting:
![image](https://user-images.githubusercontent.com/44578831/105253847-4a79b900-5b4e-11eb-9df4-8c299d55bfd1.png)

I am not a C++ guy, so I have no clue how to fix this issue.  Any help is appreciated.

**Comment by champnic** [comment]
@HoldenPCaulfield Can you share the call stack for when this hit?

**Comment by HoldenPCaulfield** [comment]
Today I reBuild it, run it and it appears to work.   So I cannot show the call stack lol.   WTF.   I hate it when bugs are not reproduceable.   This never happened when I wrote code for the mainframes :)
![image](https://user-images.githubusercontent.com/44578831/105434682-0a880400-5c2a-11eb-955a-429dbc3e2015.png)

**Comment by champnic** [comment]
Classic :D 

If you do see it again and catch the stack please let me know and I can reopen this issue.
