### ISSUE TITLE
Sample app only for netcoreapp3.0?

### ISSUE THREAD

**Issue by moses70** [MicrosoftEdge/WebView2Samples#79]
Tried to run the WPF sample app with both netcoreapp3.1 or net5.0-windows.
Neither seem to work. They are crashing when the "Go" button is pressed.

Do I have to install the obsolete 3.0 version to get it running?

**Comment by jarno9981** [comment]
Whice code are you using to navigatie

**Comment by moses70** [comment]
This happens on any URL. I tried the default and I tried several others, like www.microsoft.com and www.heise.de.
Besides, also the start screen looks really broken.

**Comment by jarno9981** [comment]
Only with url with my doensn't work but if i typer for example cow i will navigatie to google with cow a search but for urls i get get error without https or http
