### ISSUE TITLE
WinformExample Transparency Exception

### ISSUE THREAD

**Issue by LiorBanai** [MicrosoftEdge/WebView2Samples#81]
Hi,
I'm getting the following error when in the example I switch to Transparent background
![image](https://user-images.githubusercontent.com/36262995/108995792-44737c80-76a6-11eb-84e9-b2b1ce04cb14.png)

**Comment by champnic** [comment]
Hey @LiorBanai - The new DefaultBackgroundColor API is experimental, so to try out this feature you will need to use a newer runtime like the latest Microsoft Canary or Dev channel. That said, we should gracefully handle the case of using the older runtime, so I'm going to file a bug to fix this. Thanks!

**Comment by LiorBanai** [comment]
I guess I should have mentioned that I'm using the newest runtime...

**Comment by LiorBanai** [comment]
Maybe it is good idea to show which runtime is installed to the user in the examples

**Comment by champnic** [comment]
Hm - if you already have the stable WebView2 Runtime installed it might get defaulted to using that one. You can reverse the runtime search order by setting this environment variable:
`Environment.SetEnvironmentVariable("WEBVIEW2_RELEASE_CHANNEL_PREFERENCE", "1");`

Yes, we know this is currently clunky (why should you have to set an environment variable to make the sample app run correctly?) and already have a few existing workitems to improve this :)

**Comment by champnic** [comment]
If you run the Win32 version of the sample app (WebView2APISample project) the launch page will show you what runtime is being used.

**Comment by LiorBanai** [comment]
I'll check this. Thanks!

**Comment by LiorBanai** [comment]
Hi @champnic, with the Environment Variable the transparency does work but the events does not propagates the control behind the webview. 

Is it not supported?

in the image below I have transparent page but the button is not clickabe...

![image](https://user-images.githubusercontent.com/36262995/109382084-eaadc500-78e6-11eb-9372-34343cc17329.png)

**Comment by champnic** [comment]
Correct - I see you opened an issue on our feedback repo so we'll track this issue using that:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1004

Thanks!
