### ISSUE TITLE
where is HostObjectSample_h.h?

### ISSUE THREAD

**Issue by laizewei** [MicrosoftEdge/WebView2Samples#89]
where is HostObjectSample_h.h?

**Comment by peiche-jessica** [comment]
Hello @laizewei,

HostObjectSample_h.h is a header file generated by building [HostObjectSample.idl](https://github.com/MicrosoftEdge/WebView2Samples/blob/5d6438769cde5445884a23a5516dfce889858591/SampleApps/WebView2APISample/HostObjectSample.idl).

Btw, we also have [WebView2Feedback](https://github.com/MicrosoftEdge/WebView2Feedback/) for general WebView2 questions/feedback!
