### ISSUE TITLE
How do I render WebView2 in my application?

### ISSUE THREAD

**Issue by laizewei** [MicrosoftEdge/WebView2Samples#91]
https://github.com/laizewei/ExduiR/blob/master/src/Class_WebView_ex.cpp

How do I render WebView2 in my application?

**Comment by champnic** [comment]
Please take a look at our[ Win32 Getting Started Guide](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/win32), or the Win32 sample app. It looks like you're creating the Environment, and so the next step will be to create the Controller/CompositionController and then get the ICoreWebView2 itself.

**Comment by laizewei** [comment]
I used D2D context to render the component, but I couldn't draw WebView2. How to render it?

**Comment by champnic** [comment]
D2D integration is tracked here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/20
