### ISSUE TITLE
Qeustion How to Get EBWebView folder

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Samples#97]
EBWebView i want that folder to get to temp so webview2 can write data to it and read 

C#
winforms 
.net framework 4.8

**Comment by jarno9981** [comment]
@champnic

**Comment by champnic** [comment]
You can set the user data folder (which contains the EBWebView) through [CreationProperties](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.creationproperties?view=webview2-dotnet-1.0.864.35) and the UserDataFolder property there, or when creating the [environment](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=webview2-dotnet-1.0.864.35). Thanks!
