### ISSUE TITLE
Background Navigation

### ISSUE THREAD

**Issue by ThSeyfarth** [MicrosoftEdge/WebView2Samples#98]
Hello Dears,
i do have at least 2 difficuilts where i get stuck currently. Essentially i am trying to Re-Navigate to URLs triggered by Background-Process, not triggered by Buttons or Keyentering.
Unfortunately in both Templates which i have written i couldn´t Re-Navigate URL´s.

My first template is called by a Process out of C#. As Example i create around 7 seconds later after startet the Process a File which is reading by the first template after 15 seconds. Reading of the File is working well. But no Event is firing to Re-Navigate.

My second template looks like that i have created a wpf usercontrol dll which get called by Method with params. But even the same picture no action is fired.

Methods get params and were called in both cases. 

Do i need to find out which currently webview2 id is used to navigating via background?

Thank you for your suggestions

**Comment by champnic** [comment]
Hey @ThSeyfarth - do you have some sample code or app you could share that illustrates the issue you are running into? If you are trying to navigate to the same url I don't believe that does anything, but you could try calling `WebView2.Reload()` instead.

**Comment by ThSeyfarth** [comment]
Hey @champnic yap here are my snippets:
First-Template "Process calling deploed API":
"WebView-Console (where the Process starts the Webview2 API"
Process.cs:
private void Execute()
        {
            var x = @"C:\Users\source\repos\WebView2_Edge_Browser\WebView2_Edge_Browser\bin\Release\";
            string fileName = @"C:\Users\\source\repos\WebView2_Edge_Browser\WebView2_Edge_Browser\bin\Microsoft.WebView2.FixedVersionRuntime.91.0.864.48.x64\Microsoft.WebView2.FixedVersionRuntime.91.0.864.48.x64";
            //string url = "https://whatsmybrowser.org";
            string url = "https://google.de";
            
            webView_Process.EnableRaisingEvents = true;
            ProcessStartInfo infos = new ProcessStartInfo();
                infos.FileName = x+"WebView2_Edge_Browser.exe";
                infos.WindowStyle = ProcessWindowStyle.Hidden;
                infos.UseShellExecute = false;
                infos.CreateNoWindow = true;
                infos.Arguments = "\"" + fileName + "\"" + " \"" + url + "\"";
                infos.RedirectStandardOutput = true;
                infos.RedirectStandardError = true;
            webView_Process.StartInfo = infos;
                
            webView_Process.Start();
            /* used to create json-File for new URL */
            System.Timers.Timer currTimer = new System.Timers.Timer();
            currTimer.Elapsed += new ElapsedEventHandler(ReURL);
            currTimer.Interval = 8000;
            currTimer.Enabled = true;

            webView_Process.BeginOutputReadLine();
            webView_Process.BeginErrorReadLine();
            webView_Process.WaitForExit();
            webView_Process.Close();
            webView_Process.Dispose();
            webView_Process = null;
        }

private void ReURL(object source, ElapsedEventArgs e)
 {
            Dictionary<string, string> navigation = new Dictionary<string, string>
            {
                {"action","navigation"},
                {"url","https://www.newtonsoft.com/json" }
            };
            string json_URL = JsonConvert.SerializeObject(navigation, Formatting.Indented);

            using(StreamWriter jsonFile = File.CreateText(@"C:\@sonstiges\nav.json"))
            {
                JsonSerializer serializer = new JsonSerializer();
                serializer.Serialize(jsonFile, navigation);
            }
 }

"WebView_Edge_Browser-API"
App.xaml.cs

private void Application_StartUp(object sender, StartupEventArgs e)
{
           if(e.Args.Length == 2)
           {
                  MainWindow CurWindow = new MainWindow(e.Args[0], e.Args[1]);
                  CurWindow.Show();
             }
 }

MainWindow.xaml.cs
 public string URL { get; set; }
 public string EXEC_FILE { get; set; }
 public MainWindow(string CabFileLocation, string UrlConnection)
 {
            this.URL = UrlConnection;
            this.EXEC_FILE = CabFileLocation;

            InitializeComponent();
            InitializeAsync();
            RecursiveAsyncURL();
            
   }
     private async void InitializeAsync()
        {
            var env = await CoreWebView2Environment.CreateAsync(EXEC_FILE);
            await webView.EnsureCoreWebView2Async(env);
            webView.Source = new Uri(URL);
           
           /* **Timer is used to Read URL File** */ 
           System.Timers.Timer currTimer = new System.Timers.Timer();
            currTimer.Elapsed += new ElapsedEventHandler(ReCheckURL);
            currTimer.Interval = 15000;
            currTimer.Enabled = true;
        }

        private async void RecursiveAsyncURL()
        {
            await webView.EnsureCoreWebView2Async(null);
            webView.CoreWebView2.WebMessageReceived += UpdateUrl;
            await webView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window.chrome.webview.postMessage(window.document.URL);");
        }

        private void UpdateUrl(object sender, CoreWebView2WebMessageReceivedEventArgs args)
        {
            string curURL = args.TryGetWebMessageAsString();
            webView.CoreWebView2.PostWebMessageAsString(curURL);
        }

        private void ReCheckURL(object source, ElapsedEventArgs e)
        {
            string CheckingPath = @"C:\@sonstiges\nav.json";
            if (File.Exists(CheckingPath))
            {
                using (StreamReader jsonReader = File.OpenText(CheckingPath))
                {
                    JsonSerializer serializer = new JsonSerializer();
                    ReURL currURL = (ReURL)serializer.Deserialize(jsonReader, typeof(ReURL));
                    if (currURL.Action.Equals("navigation"))
                    {
                        
                        /* **is to used to Check if the Method is working** 
                        string path = @"C:\@sonstiges\re.txt";
                        if (!File.Exists(path))
                        {
                            File.Create(path).Dispose();
                            using (TextWriter tw = new StreamWriter(path))
                            {
                                tw.WriteLine(currURL.URL + Environment.NewLine);

                            }
                        }
                        else if (File.Exists(path))
                        {
                            File.AppendAllText(path, currURL.URL + Environment.NewLine);
                        }
                        */
                        // tried with Navigate
                        // **webView.CoreWebView2.Navigate(URL);**
                        // tried with new Source
                        // **webView.Source = new Uri(URL);**
                     }
                }
            }
        }

**Comment by champnic** [comment]
Thanks for sharing the code! Which part is not working as expected?

**Comment by ThSeyfarth** [comment]
Hello champnic,
here´s the issue, what isnt working.

private void ReCheckURL(object source, ElapsedEventArgs e)
{        
                        ....
                        // tried with Navigate
                        // **webView.CoreWebView2.Navigate(URL);**
                        // tried with new Source
                        // **webView.Source = new Uri(URL);**
}
@this point here isnt working as excpected. In my mind i would get a resourcing to the new URL. But isnt working. 
Starting the Program, the first url navigating at working well. But if the File is extracted WebView doesnt renavigate. 
I had written in File when the json-File was reading to checkout if the parameters are correct.

**Comment by champnic** [comment]
Gotcha. It's By Design that setting the Source to be the same url it currently is is a no-op. Can you try using the `WebView2.Reload()` function instead? Thanks!
